### ISSUE TITLE
Check if a link is already posted

### ISSUE THREAD

**Issue by indeedwatson** [lhc-sudo/bach-bot#9]
This is just a suggestion, but sometimes the bot will post the link even if the comment it's responding to already has a link to youtube.

**Comment by lhc-sudo** [comment]
Hmm, I'll take a look and try to add a RegEx match for `youtube.com`, `youtu.be` etc. 
Though yes, the bot doing that is pretty redundant.

**Comment by lhc-sudo** [comment]
Or even just search through for the exact YouTube link rather than any one, which might make more sense.

**Comment by indeedwatson** [comment]
Awesome, also I used a time stamp in the url, so regex for that might be useful.

Great bot btw!

**Comment by lhc-sudo** [comment]
Well... it turns out that the functions that make up my code are really badly interweaved, meaning that it's surprisingly hard to do the check as all the required data is spread throughout isolated functions in the code. I'll find a way though!

**Comment by indeedwatson** [comment]
Totally been there, refactoring could be good practice :)

**Comment by lhc-sudo** [comment]
Done! After navigating the spaghetti code, I hope this works...

**Comment by lhc-sudo** [comment]
As it happens, no it does not work. The pull request broke it - brilliant. Back to debugging...

**Comment by lhc-sudo** [comment]
Pull request #11 should *crosses fingers* fix it this time.
